coverage:
  range: "45...90"
  precision: 2
  round: down
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: "2%"
  status:
    project:
      default:
        threshold: "2%"
comment:
  layout: "header, diff, tree, sunburst"
  require_changes: true

